input {
  udp {
    port => 12201
    codec => json
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://project2-elasticsearch:9200"]
    index => "project2-logs"
  }

  stdout {
    codec => rubydebug
  }
}
