input {
  beats {
    port => 5044
  }
}

filter {
  if [service] == "nginx" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }

    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }

    mutate {
      convert => {
        "response" => "integer"
        "bytes" => "integer"
      }
    }
  }

  if [service] == "flask" {
    json {
      source => "message"
    }

    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
}

  if [service] == "postgres" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:pg_time} %{WORD:pg_tz} \[%{NUMBER:pg_pid}\] %{WORD:pg_level}:\s+%{GREEDYDATA:pg_message}" }
    }

    date {
      match => [ "pg_time", "yyyy-MM-dd HH:mm:ss.SSS" ]
      timezone => "UTC"
      target => "@timestamp"
    }
  }

output {
  if [service] == "nginx" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
  }

  if [service] == "flask" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "flask-logs-%{+YYYY.MM.dd}"
    }
  }

  if [service] == "postgres" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "postgres-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
